### ISSUE TITLE
Suspicious code in semigroups.cc init_idempotents

### ISSUE THREAD

**Issue by ChrisJefferson** [james-d-mitchell/libsemigroups#101]
On line 1032 of semigroups.cc, we have:     total_load += complexity * (_nr - _lenindex[threshold_length - 1]);

This is being flagged by a memory checker. I wonder if threshold_length can be 0, and then this is -1? Alternatively, in line 1016, could _linindex.size() be 0 or 1, so doing -2 will underflow?

**Comment by james-d-mitchell** [comment]
This is definitely a bug, I am fixing it now.
