### ISSUE TITLE
Provide a means to determine version

### ISSUE THREAD

**Issue by dimpase** [james-d-mitchell/libsemigroups#105]
Could you provide a way to figure out the version from installed files, e.g. via `pkg-config`, or a custom `libsemigroups-config` shell script? (one should not assume that complete source is available, rather it's what's installed by `make install`)

This is related to https://trac.sagemath.org/ticket/27396 (create Sage libsemigroup package) and https://trac.sagemath.org/ticket/27295 (add semigroups to GAP packages in Sage). 

(Edit - I realised that VERSION is for the the current master, hence the edit...)

**Comment by dimpase** [comment]
@nthiery

**Comment by james-d-mitchell** [comment]
The last released version of libsemigroups is 0.6.4, and the file `VERSION` contains the version number. It's better not to use the unreleased `master` branch in other projects. There is also a macro `LIBSEMIGROUPS_PACKAGE_VERSION` defined in `libsemigroups-config.h`, which can be used to get the version number. Do you need something further than this?

**Comment by james-d-mitchell** [comment]
Also there is `LIBSEMIGROUPS_VERSION`, which is equal to `LIBSEMIGROUPS_PACKAGE_VERSION` and `libsemigroups-config.h` is installed when libsemigroups is installed via `make install`.

If this is not what you were looking for, then can you please provide more details?

**Comment by dimpase** [comment]
I would much prefer letting a pkg-config-provided autoconf macro
PKG_CHECK_smthng to do the job than to mess around with grep or
AC_RUN_IFELSE to get the version info.

 Needless to say this would also simplify GAP's semigroup package
configuration, having this readily available.

**Comment by james-d-mitchell** [comment]
I don't really understand, can you describe the context you are trying to get the version number in? There aren't enough details in this issue for me to know what you want. Please elaborate.

**Comment by dimpase** [comment]
for instance,

./configure —prefix=blah && make && make install

will install the library in blah, a location not necessarily in the default
path of the compiler and linker.
Thus one would need to find the location and compiler/linker flags.

In particular if this installation is not done in lockstep with the
installation of a GAP or another package that needs it, we have a discovery
problem to solve.

**Comment by james-d-mitchell** [comment]
Libsemigroups is a C++ library independent of GAP, I have no idea what you’re trying to do. Can you please provide a minimal complete example of what you are trying to do and what goes wrong?

**Comment by dimpase** [comment]
Please see https://github.com/james-d-mitchell/libsemigroups/pull/106

Without something like this it is a major pain for users of the library to figure out version, flags to use, etc -- in particular autoconf scripts its validation get needlessly tricky.

**Comment by james-d-mitchell** [comment]
Ah great, I see now, thanks for the PR I’ll review it tomorrow.

**Comment by james-d-mitchell** [comment]
Resolved in v0.6.5.
