### ISSUE TITLE
unable to import semigroups in python3

### ISSUE THREAD

**Issue by le27** [james-d-mitchell/libsemigroups#12]
`le27@le27-VirtualBox:~$` git clone https://github.com/james-d-mitchell/libsemigroups.git
Cloning into 'libsemigroups'...
remote: Counting objects: 843, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 843 (delta 14), reused 0 (delta 0), pack-reused 807
Receiving objects: 100% (843/843), 488.01 KiB | 428.00 KiB/s, done.
Resolving deltas: 100% (566/566), done.
Checking connectivity... done.
le27@le27-VirtualBox:~/libsemigroups$ git checkout autotools
Branch autotools set up to track remote branch autotools from origin.
Switched to a new branch 'autotools'
le27@le27-VirtualBox:~/libsemigroups$ ./autogen.sh
+ dirname ./autogen.sh
+ autoreconf -vif .
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory config
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:14: installing 'config/ar-lib'
configure.ac:14: installing 'config/compile'
configure.ac:28: installing 'config/config.guess'
configure.ac:28: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
Makefile.am:34: warning: wildcard semigroups/*.h: non-POSIX variable name
Makefile.am:34: (probably a GNU make extension)
Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
le27@le27-VirtualBox:~/libsemigroups$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
no
checking whether ln -s works... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for inline... inline
checking for int64_t... yes
checking for size_t... yes
checking for uint64_t... yes
checking for ptrdiff_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for gettimeofday... yes
checking for memset... yes
checking for pow... yes
checking for sqrt... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
le27@le27-VirtualBox:~/libsemigroups$ make
  CXX      semigroups/blocks.lo
  CXX      semigroups/cong.lo
  CXX      semigroups/elements.lo
  CXX      semigroups/semigroups.lo
  CXX      semigroups/rws.lo
  CXX      semigroups/rwse.lo
  CXX      semigroups/cong/kbfp.lo
  CXX      semigroups/cong/p.lo
  CXX      semigroups/cong/kbp.lo
  CXX      semigroups/cong/tc.lo
  CXX      semigroups/util/uf.lo
  CXXLD    libsemigroups.la
ar: `u' modifier ignored since `D' is the default (see `U')
le27@le27-VirtualBox:~/libsemigroups$ sudo make install
make[1]: Entering directory '/home/le27/libsemigroups'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libsemigroups.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libsemigroups.so.0.0.0 /usr/local/lib/libsemigroups.so.0.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libsemigroups.so.0.0.0 libsemigroups.so.0 || { rm -f libsemigroups.so.0 && ln -s libsemigroups.so.0.0.0 libsemigroups.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libsemigroups.so.0.0.0 libsemigroups.so || { rm -f libsemigroups.so && ln -s libsemigroups.so.0.0.0 libsemigroups.so; }; })
libtool: install: /usr/bin/install -c .libs/libsemigroups.lai /usr/local/lib/libsemigroups.la
libtool: install: /usr/bin/install -c .libs/libsemigroups.a /usr/local/lib/libsemigroups.a
libtool: install: chmod 644 /usr/local/lib/libsemigroups.a
libtool: install: ranlib /usr/local/lib/libsemigroups.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/include'
 /bin/mkdir -p '/usr/local/include/semigroups/cong'
 /usr/bin/install -c -m 644  semigroups/cong/kbfp.h semigroups/cong/p.h semigroups/cong/kbp.h semigroups/cong/tc.h '/usr/local/include/semigroups/cong'
 /bin/mkdir -p '/usr/local/include/semigroups/util'
 /usr/bin/install -c -m 644  semigroups/util/recvec.h semigroups/util/report.h semigroups/util/timer.h semigroups/util/uf.h '/usr/local/include/semigroups/util'
 /bin/mkdir -p '/usr/local/include/semigroups'
 /usr/bin/install -c -m 644  semigroups/blocks.h semigroups/cong.h semigroups/elements.h semigroups/semigroups.h semigroups/rws.h semigroups/rwse.h semigroups/semiring.h '/usr/local/include/semigroups'
make[1]: Leaving directory '/home/le27/libsemigroups'
le27@le27-VirtualBox:~/libsemigroups$ sudo ldconfig
le27@le27-VirtualBox:~/libsemigroups$ cd python-bindings/
le27@le27-VirtualBox:~/libsemigroups/python-bindings$ pip install --user . --upgrade
Processing /home/le27/libsemigroups/python-bindings
Building wheels for collected packages: libsemigroups-python-bindings
  Running setup.py bdist_wheel for libsemigroups-python-bindings ... done
  Stored in directory: /home/le27/.cache/pip/wheels/cf/3b/bd/5db4c4c77fd834069579816725799392863f0320fe19347886
Successfully built libsemigroups-python-bindings
Installing collected packages: libsemigroups-python-bindings
  Found existing installation: libsemigroups-python-bindings 0.0.0
    Uninstalling libsemigroups-python-bindings-0.0.0:
      Successfully uninstalled libsemigroups-python-bindings-0.0.0
Successfully installed libsemigroups-python-bindings-0.0.0
le27@le27-VirtualBox:~/libsemigroups/python-bindings$ pip3 install --user . --upgrade
Processing /home/le27/libsemigroups/python-bindings
Building wheels for collected packages: libsemigroups-python-bindings
  Running setup.py bdist_wheel for libsemigroups-python-bindings ... done
  Stored in directory: /home/le27/.cache/pip/wheels/cf/3b/bd/5db4c4c77fd834069579816725799392863f0320fe19347886
Successfully built libsemigroups-python-bindings
Installing collected packages: libsemigroups-python-bindings
  Found existing installation: libsemigroups-python-bindings 0.0.0
    Uninstalling libsemigroups-python-bindings-0.0.0:
      Successfully uninstalled libsemigroups-python-bindings-0.0.0
Successfully installed libsemigroups-python-bindings-0.0.0
le27@le27-VirtualBox:~/libsemigroups/python-bindings$ python3
Python 3.6.0 (default, Feb 15 2017, 18:12:45) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from semigroups import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'semigroups'
`

**Comment by james-d-mitchell** [comment]
This is no longer an issue.
