### ISSUE TITLE
NaturalSemiring assertion failure (GAP)

### ISSUE THREAD

**Issue by mtorpey** [james-d-mitchell/libsemigroups#22]
When GAP is loaded with Semigroups and libsemigroups (most recent `master` version of all three) and Semigroups is compiled with `make debug`, there is an assertion failure in `semitrans.tst`:

```
gap> Test("tst/standard/semitrans.tst");
gap: src/libsemigroups/semiring.h:288: libsemigroups::NaturalSemiring::NaturalSemiring(int64_t, int64_t): Assertion `this->threshold() > 0' failed.
/home/mtorpey/bin/gap: line 2: 30040 Aborted                 (core dumped) /home/mtorpey/gap/bin/gap.sh -m 2g "$@"
```

I'm listing this for libsemigroups, as I'm guessing that's where the problem lies.

This doesn't show up unless `make debug` is used (being an assertion failure).

I think this was compiled with GCC 5.4.0.

**Comment by james-d-mitchell** [comment]
Fixed in v0.2.1
