### ISSUE TITLE
UF not being linked properly?

### ISSUE THREAD

**Issue by mtorpey** [james-d-mitchell/libsemigroups#25]
Looks like another boring compiler thing, presumably either Clang vs GCC or Apple vs Linux.

When I run GAP and test congruences when libsemigroups is on the `master` branch, I get a messed up error:
```gap
gap> Test("tst/standard/cong.tst");
/home/mtorpey/gap/gap: symbol lookup error: /home/mtorpey/gap/pkg/semigroups/bin/x86_64-pc-linux-gnu-gcc-default64/semigroups.so: undefined symbol: _ZN13libsemigroups2UFC1Em
```
but this doesn't happen in the `stable-0.1` branch.

The problem is introduced by commit `2600db`: "cong: include header not source file", which @james-d-mitchell pushed a couple of days ago. The problem is fixed by basically reincluding `uf.cc`, as in this patch:
```diff
diff --git a/cong/p.cc b/cong/p.cc
index 747f6ef..34c1019 100644
--- a/cong/p.cc
+++ b/cong/p.cc
@@ -29,6 +29,8 @@
 
 #include <utility>
 
+#include "../util/uf.cc"
+
 namespace libsemigroups {
 
   Congruence::P::P(Congruence& cong)
```
I don't understand all the `#include` stuff, so maybe this patch isn't ideal.  But it does fix it on my PC.

**Comment by mtorpey** [comment]
By the way, this isn't urgent for me, as I can easily develop against `stable-0.1` for now.

**Comment by james-d-mitchell** [comment]
Fix in commit 09a590c

**Comment by mtorpey** [comment]
The commit you mention was already in `master` before I posted this issue, and doesn't fix the problem for me.  Not sure why not.

**Comment by james-d-mitchell** [comment]
Hmm, can you confirm that you have a uf.o file in test/bin/until?

**Comment by james-d-mitchell** [comment]
Oh wait, can you check if uf.cc is one of the sources in the Makefile.am of Semigroups? If not add it, with appropriate path prefix and autogen.sh configure make

**Comment by james-d-mitchell** [comment]
My last comment is the correct way to fix this.

**Comment by mtorpey** [comment]
That suggestion works.  I've put it in [a pull request](https://github.com/gap-packages/Semigroups/pull/268).
